[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_POSTHOG_KEY"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "http://menclmax.com/*"
  to = "https://menclmax.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.menclmax.com/*"
  to = "https://menclmax.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.menclmax.com/*"
  to = "https://menclmax.com/:splat"
  status = 301
  force = true

